/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Oshen Sathsara <oshensathsara2003@gmail.com>
 */
public class ToastDialog extends javax.swing.JDialog {

    public static final Color SUCCESS_COLOR = new Color(89, 215, 51);
    public static final Color ERROR_COLOR = new Color(220, 26, 26);
    public static final Color WARNING_COLOR = new Color(255, 215, 50);

    /**
     * Creates new form ToastDialog
     */
    public ToastDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setOpaque(false);
        getContentPane().setBackground(WARNING_COLOR);
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    public static void showToast(Component parent, String titleText, String descriptionText, Color bgColor) {
        Frame frame = JOptionPane.getFrameForComponent(parent);
        ToastDialog dialog = new ToastDialog(frame);

        dialog.title.setText(titleText);
        dialog.description.setText(descriptionText);
        dialog.getContentPane().setBackground(bgColor);

        if (parent != null) {
            Point loc = parent.getLocationOnScreen();
            dialog.setLocation(loc.x + parent.getWidth() / 2 - dialog.getWidth() / 2,
                    loc.y + parent.getHeight() - 700);
        }
        // for auto closing the dialog
        Timer timer = new Timer(2500, e -> dialog.dispose());
        timer.setRepeats(false);
        timer.start();

        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusableWindowState(false);
        setUndecorated(true);
        setResizable(false);

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(description)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
